### ISSUE TITLE
Salt Pill Design

### ISSUE THREAD

**Issue by rexgarland** [stanford-physics108-2015/cryo#13]
@stanford-physics108-2015/owners 

With which materials can we construct the salt pill to reduce eddy currents? Nylon? It must be a material we can drill precisely to create a ~1mm shell thickness.
Can we still include a metal poll down the center of the pill to conduct heat from the thermometer to the salt?

**Comment by zmwangx** [comment]
We were discussing the possibility of using a mold to shape the pill to dispense with a container. Not sure  if it's feasible (did we reject this idea?). The reason is that a container would add considerable thermal mass. Say the entire cylinder has 5mm radius, and the container shell is 1mm thick. Then the ratio of the volumes of the shell and the salt & epoxy mix would be (5^2-4^2):4^2 = 9:16. Currently we expect the salt to occupy less than half of the volume of the salt & epoxy mix, then the volume of the shell would be ridiculously large.

At any rate, we decided to use as little metal as possible, preferably none.

**Comment by rexgarland** [comment]
That's a good point. Why can't we push up the radius to 8mm (giving us 1.75mm clearance with the vacuum wall)? That would give us a ratio of ~3.3 salt+epoxy volume to shell volume.

**Comment by zmwangx** [comment]
> Why can't we push up the radius to 8mm (giving us 1.75mm clearance with the vacuum wall)?

The bore diameter of the magnet is 3/4in or 19mm. The tube diameters are standardized, so we might be forced to use a 5/8in tube, which leaves us <16mm of outer diameter. We asked about the wall thickness on Friday but I don't think we got a definitive answer. Anyway, the wall of a vacuum can can't be too thin, so let's assume it's 1mm thick (maybe even thicker). That leaves us <14mm (without clearance). Assuming 1.5–2mm of clearance, the sample diameter has to be ~10mm. Even if we can fit a 3/4in tube into the bore of the magnet, we'll have at most ~13mm of diameter.

**Comment by marxwillia** [comment]
We talked to David on Friday, and he said that after the epoxy in the salt pill has been hardened, we can get good thermal contact with the thermometer simply by pressing the thermometer on the pill.  For this reason, I believe we decided that a metal rod going through the pill to connect to the thermometer is unnecessary.

**Comment by zmwangx** [comment]
@marxwillia I think David meant "good contact", but not necessarily "good thermal contact". He wanted us to calculate, but honestly I see no way to carry it out. Too many empirical parameters are missing.
