### ISSUE TITLE
Heat conduction between salt pill and thermometer (and the competition with heat leak) — timescale estimates

### ISSUE THREAD

**Issue by zmwangx** [stanford-physics108-2015/cryo#9]
Heat conduction rate is our main concern because if we can't get our salt pill and thermometer into equilibrium before heat leak brings the salt pill back to the bath temperature, we're screwed.

Ben's initial estimate of the time to warm up the pill was disastrous, but there's room for improvement — anchor at 1.5K rather than 77K, thinner (and possibly longer, with a price — inductance) wires, etc.

During yesterday's (01/16/2015) meeting several possible models of ensuring better heat conduction was discussed, including mesh, pellets, or epoxy (did I miss something?). The major embarrassment is that there's little hope of estimating the rate of heat conduction analytically. Alex suggested that maybe we could have an order-of-magnitude estimate.

**Comment by zmwangx** [comment]
@bvlehm @marxwillia @rexgarland

**Comment by bvlehm** [comment]
@zmwangx @rexgarland @marxwillia Good news! I found an error in my heat leak calculation—I wrote down the height of the salt pill as 0.2 cm instead of 2.0 cm. The revised calculation would give us about five seconds before we get back up to bath temperature.

That still isn't great, given that the demagnetization takes "a few seconds", but it's an improvement. It certainly makes me feel a lot more confident about a design with the commercial magnet, where I estimate we could fit five times as much salt as what I assumed for that calculation. If we additionally heat-sink the wire to helium, I think we'll be fine. I'd feel a lot better if we could physically switch the wires, but we may be okay even without that.

Note, however, that this calculation was a very simple estimate with some bad assumptions. We should think about it a little more carefully before we make final design decisions.

**Comment by rexgarland** [comment]
From 1/19 meeting at Huang:

Our current thoughts for conduction include mixing the salt with epoxy (how hard would it be to just mix in a bowl) and somehow placing the salt in thermal contact with a metal mesh / metal wires (see [Benford_1994_Cryo_Hagmann.pdf](https://www.dropbox.com/s/go7eyho9vg3irwm/Benford_1994_Cryo_Hagmann.pdf?dl=0)).

**Comment by zmwangx** [comment]
There's little we could do.
